import { RaceView } from "@/components/RaceView";
import { loadDocLean, loadManifest } from "@/lib/results";

export default async function Home() {
  const manifest = await loadManifest();
  const docs = await Promise.all(
    manifest.docs.map((d) => loadDocLean(d.doc_id)),
  );

  // Fixture data exists so the UI can be reviewed before a paid precompute run.
  // Shipping it as though it were real measurement would be the worst outcome
  // this project could produce, so it announces itself rather than relying on
  // whoever deploys to remember.
  const isFixture = manifest.fixture || docs.some((d) => d.license === "fixture");

  return (
    <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8">
      {isFixture ? (
        <div
          role="alert"
          className="mb-8 rounded-md border border-[#d1382a] bg-[#2a1210] px-4 py-3 text-sm leading-relaxed text-text"
        >
          <strong className="font-medium">
            These are fixture numbers, not measurements.
          </strong>{" "}
          The results in <code className="text-text-dim">results/</code> were
          generated by <code className="text-text-dim">make_fixtures.py</code> so
          the interface could be reviewed without spending anything. Every figure
          on this page is synthetic. Run{" "}
          <code className="text-text-dim">python -m docrace.precompute</code> to
          replace them.
        </div>
      ) : null}

      <header className="max-w-3xl space-y-4">
        <p className="text-xs uppercase tracking-[0.18em] text-accent">DocRace</p>
        <h1 className="text-2xl font-medium leading-snug text-text sm:text-3xl">
          Everyone has an opinion about RAG vs. long context. This one you can run.
        </h1>
        <p className="text-base leading-relaxed text-text-dim">
          Ask a question of a document, watch six extraction strategies answer it
          side by side, and see exactly what each one cost you.
        </p>

        {/* The caveat goes above the fold, not in a footnote. Three documents
            cannot support a claim about which strategy is better in general, and
            pretending otherwise invites the one criticism there is no answer to. */}
        <div className="rounded-md border border-border bg-bg-raised px-4 py-3 text-sm leading-relaxed text-text-dim">
          <strong className="font-medium text-text">
            This is not a benchmark.
          </strong>{" "}
          Three documents cannot tell you which strategy is better in general, and
          nothing here claims to. It is a decision tool: the numbers are real
          measurements on these three documents with these questions, and the point
          is to let you watch how the answer changes when the document does.
        </div>
      </header>

      <div className="mt-10">
        <RaceView manifest={manifest} docs={docs} />
      </div>

      <footer className="mt-14 space-y-2 border-t border-border pt-6 text-sm text-text-faint">
        <p>
          All results precomputed with{" "}
          <span className="text-text-dim">{manifest.model}</span> on{" "}
          <span className="tnum text-text-dim">
            {manifest.computed_at.slice(0, 10)}
          </span>
          , priced against the rate card of{" "}
          <span className="tnum text-text-dim">{manifest.pricing_snapshot}</span>.
          Model prices change; these numbers do not update themselves.
        </p>
        <p>
          The site runs in replay mode: every answer was streamed once, offline,
          and is replayed from committed JSON. Nothing here calls an API at request
          time.
        </p>
      </footer>
    </main>
  );
}
